//! Manifest → `pipelines.toml`.
//!
//! The output is written for a human to read and edit, not just for the parser: models
//! that cannot be streamed appear as commented-out entries carrying their reason, so the
//! generated file is also the report. Regenerating after a dbt change shows what moved.

use crate::config::Config;
use crate::dbt::analyze::{analyze_all, Verdict};
use crate::dbt::{Manifest, UriTemplate};
use crate::error::{Error, Result};

/// Prefix for generated `app_id`s. The offset key must be stable forever, so it is
/// derived from the model name and nothing that moves (not the schema, not the path).
const APP_ID_PREFIX: &str = "ddi";

pub fn app_id_for(model: &str) -> String {
    format!("{APP_ID_PREFIX}.{model}")
}

/// Render a full config for every streamable model in `manifest`.
pub fn to_toml(manifest: &Manifest, cfg: &Config) -> Result<String> {
    let template = cfg.dbt.uri_template.as_deref().ok_or_else(|| {
        Error::Config(
            "no [dbt].uri_template in the config. The manifest names relations \
             (schema.table) but ddi needs storage URIs, e.g.\n\n  [dbt]\n  uri_template = \
             \"abfss://lake@acct.dfs.core.windows.net/{schema}/{name}\"\n"
                .into(),
        )
    })?;
    let template = UriTemplate::new(template);

    let mut out = String::new();
    out.push_str(
        "# Generated by `ddi dbt convert`. Regenerate after changing the dbt project.\n\
         #\n\
         # Models that cannot be streamed are listed at the end with the reason.\n\n",
    );

    if let Some(w) = &cfg.dbt.watermark_uri {
        out.push_str(&format!(
            "[dbt]\nwatermark_uri = {w:?}\n\n\
             # Every pipeline below shares its target with dbt, so each one resumes from\n\
             # this table after a nightly rebuild rather than from its own txn offset.\n\n"
        ));
    }

    let verdicts = analyze_all(manifest);
    let mut streamable = 0;

    for v in &verdicts {
        let Verdict::Streamable(s) = v else { continue };
        streamable += 1;

        let source_node = manifest
            .node(&s.unique_id)
            .and_then(|n| n.depends_on.nodes.first())
            .and_then(|id| manifest.node(id));
        let target_node = manifest.node(&s.unique_id);

        let (Some(src), Some(tgt)) = (source_node, target_node) else {
            return Err(Error::Config(format!(
                "model {:?}: could not resolve its relations from the manifest",
                s.name
            )));
        };

        out.push_str("[[pipeline]]\n");
        out.push_str(&format!("name       = {:?}\n", s.name));
        out.push_str(&format!("app_id     = {:?}\n", app_id_for(&s.name)));
        out.push_str(&format!("source_uri = {:?}\n", template.render(src)));
        out.push_str(&format!("target_uri = {:?}\n", template.render(tgt)));
        if let Some(sql) = &s.transform_sql {
            out.push_str(&format!("transform_sql = \"\"\"\n{sql}\n\"\"\"\n"));
        }
        out.push('\n');
    }

    if streamable == 0 {
        out.push_str("# No streamable models found.\n\n");
    }

    let rejected: Vec<&Verdict> = verdicts.iter().filter(|v| !v.is_streamable()).collect();
    if !rejected.is_empty() {
        out.push_str("# ---------------------------------------------------------------\n");
        out.push_str("# Not streamable:\n");
        for v in rejected {
            if let Verdict::Rejected { name, reason } = v {
                out.push_str(&format!("#   {name}: {reason}\n"));
            }
        }
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::DbtConfig;
    use crate::dbt::{DependsOn, Node, NodeConfig};
    use std::collections::HashMap;

    fn fixture() -> Manifest {
        let mut nodes = HashMap::new();
        nodes.insert(
            "model.p.orders_header".to_string(),
            Node {
                name: "orders_header".into(),
                resource_type: "model".into(),
                schema: "silver".into(),
                compiled_code: Some(
                    "SELECT order_id, CAST(created_at AS TIMESTAMP) AS created_at \
                     FROM bronze.orders"
                        .into(),
                ),
                depends_on: DependsOn {
                    nodes: vec!["source.p.bronze.orders".into()],
                },
                config: NodeConfig {
                    materialized: Some("table".into()),
                    ..Default::default()
                },
                ..Default::default()
            },
        );
        nodes.insert(
            "model.p.daily_totals".to_string(),
            Node {
                name: "daily_totals".into(),
                resource_type: "model".into(),
                schema: "gold".into(),
                compiled_code: Some(
                    "SELECT customer_id, sum(total) AS t FROM bronze.orders GROUP BY customer_id"
                        .into(),
                ),
                depends_on: DependsOn {
                    nodes: vec!["source.p.bronze.orders".into()],
                },
                config: NodeConfig {
                    materialized: Some("table".into()),
                    ..Default::default()
                },
                ..Default::default()
            },
        );
        let mut sources = HashMap::new();
        sources.insert(
            "source.p.bronze.orders".to_string(),
            Node {
                name: "orders".into(),
                resource_type: "source".into(),
                schema: "bronze".into(),
                ..Default::default()
            },
        );
        Manifest { nodes, sources }
    }

    fn config() -> Config {
        Config {
            dbt: DbtConfig {
                uri_template: Some("s3://lake/{schema}/{name}".into()),
                watermark_uri: Some("s3://lake/meta/ddi_watermark".into()),
                ..Default::default()
            },
            ..Default::default()
        }
    }

    #[test]
    fn the_generated_config_parses_and_resolves() {
        // The point of the whole command: what comes out must go straight back in.
        let toml = to_toml(&fixture(), &config()).unwrap();
        let parsed = Config::from_toml_str(&toml)
            .unwrap_or_else(|e| panic!("generated config does not parse: {e}\n\n{toml}"));
        let resolved = parsed
            .resolve()
            .unwrap_or_else(|e| panic!("generated config does not resolve: {e}\n\n{toml}"));

        assert_eq!(resolved.len(), 1, "only the streamable model is emitted");
        let p = &resolved[0];
        assert_eq!(p.name, "orders_header");
        assert_eq!(p.app_id, "ddi.orders_header");
        assert_eq!(p.source_uri, "s3://lake/bronze/orders");
        assert_eq!(p.target_uri, "s3://lake/silver/orders_header");
        assert_eq!(
            p.watermark_uri.as_deref(),
            Some("s3://lake/meta/ddi_watermark"),
            "a dbt-shared target must carry a watermark or it can silently lose rows"
        );
    }

    #[test]
    fn rejected_models_are_reported_as_comments_with_the_reason() {
        let toml = to_toml(&fixture(), &config()).unwrap();
        assert!(toml.contains("#   daily_totals:"), "{toml}");
        assert!(toml.contains("GROUP BY"), "the reason must survive: {toml}");
    }

    #[test]
    fn a_missing_uri_template_says_what_to_add() {
        let cfg = Config::default();
        let e = to_toml(&fixture(), &cfg).unwrap_err();
        assert!(e.to_string().contains("uri_template"), "got: {e}");
    }

    #[test]
    fn app_ids_derive_from_the_model_name_only() {
        // The offset key has to be stable forever, so it must not encode anything that
        // moves — not the schema, not the storage path.
        assert_eq!(app_id_for("orders_header"), "ddi.orders_header");
    }
}
