#!/usr/bin/env python3
"""Regenerate THIRD_PARTY_NOTICES.md from Cargo.lock.

MIT and Apache-2.0 both require that copyright and licence notices survive
distribution. Shipping source satisfies that; shipping a binary or a container image
does not, unless the notices travel with it.

Licences are read from the crates vendored under the local cargo registry, so run this
after a build that has fetched every dependency:

    cargo fetch && python3 scripts/third-party-notices.py
"""
import collections
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = pathlib.Path.home() / ".cargo" / "registry" / "src"
SELF = "delta-delta-ingest"


def crates_from_lock() -> list[tuple[str, str]]:
    lock = (ROOT / "Cargo.lock").read_text()
    return re.findall(r'^name = "([^"]+)"\nversion = "([^"]+)"', lock, re.M)


def license_of(name: str, version: str) -> str | None:
    for src in REGISTRY.glob("*"):
        manifest = src / f"{name}-{version}" / "Cargo.toml"
        if manifest.exists():
            text = manifest.read_text()
            m = re.search(r'^license\s*=\s*"([^"]+)"', text, re.M)
            if m:
                return m.group(1)
            if re.search(r"^license-file", text, re.M):
                return "see the crate's bundled licence file"
            return None
    return None


def main() -> int:
    crates = [(n, v) for n, v in crates_from_lock() if n != SELF]
    rows, missing = [], []
    for name, version in sorted(crates):
        lic = license_of(name, version)
        (rows if lic else missing).append((name, version, lic))

    counts = collections.Counter(lic for _, _, lic in rows)
    out = [
        "# Third-party notices",
        "",
        "`ddi` is Apache-2.0 (see `LICENSE` and `NOTICE`). A binary build statically links",
        "the crates below. They are reproduced here to satisfy the attribution clauses of",
        "their licences, which apply whenever the binary — rather than the source — is",
        "distributed.",
        "",
        f"Generated by `scripts/third-party-notices.py` from `Cargo.lock`: "
        f"{len(rows)} crates.",
        "",
        "## Licences in use",
        "",
        "| Licence | Crates |",
        "|---|---|",
    ]
    out += [f"| {lic} | {n} |" for lic, n in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))]
    out += ["", "## Crates", "", "| Crate | Version | Licence |", "|---|---|---|"]
    out += [f"| {n} | {v} | {lic} |" for n, v, lic in rows]

    if missing:
        out += [
            "",
            "## Not resolved",
            "",
            "These were not vendored locally when this file was generated, so their licence",
            "could not be read. Run `cargo fetch` and regenerate.",
            "",
        ]
        out += [f"- {n} {v}" for n, v, _ in missing]

    out += [
        "",
        "Full licence texts are distributed with each crate in the cargo registry, and are",
        "available from the projects themselves. The common ones are reproduced in full at:",
        "",
        "- Apache-2.0: http://www.apache.org/licenses/LICENSE-2.0",
        "- MIT: https://opensource.org/licenses/MIT",
        "",
    ]
    (ROOT / "THIRD_PARTY_NOTICES.md").write_text("\n".join(out))
    print(f"wrote THIRD_PARTY_NOTICES.md: {len(rows)} crates, {len(missing)} unresolved")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
