//! `ddi` — exactly-once, append-only, stateless Delta→Delta streaming.

use std::path::PathBuf;
use std::sync::atomic::Ordering;
use std::sync::Arc;
use std::time::Duration;

use clap::{Parser, Subcommand};
use delta_delta_ingest::config::{Config, ResolvedPipeline};
use delta_delta_ingest::locate::{self, Locator};
use delta_delta_ingest::metrics::Metrics;
use delta_delta_ingest::pipeline::{Pipeline, StepOutcome};
use delta_delta_ingest::trino::TrinoClient;
use tokio::signal;
use tokio_util_shim::CancellationToken;
use tracing::{error, info, warn};

/// Minimal cancellation primitive so the binary does not pull in tokio-util for one type.
mod tokio_util_shim {
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::Arc;

    #[derive(Clone, Default)]
    pub struct CancellationToken(Arc<AtomicBool>);

    impl CancellationToken {
        pub fn new() -> Self {
            Self::default()
        }
        pub fn cancel(&self) {
            self.0.store(true, Ordering::SeqCst);
        }
        pub fn is_cancelled(&self) -> bool {
            self.0.load(Ordering::SeqCst)
        }
    }
}

#[derive(Parser)]
#[command(name = "ddi", version, about, long_about = None)]
struct Cli {
    /// Path to the pipeline config (TOML).
    #[arg(
        short,
        long,
        global = true,
        env = "DDI_CONFIG",
        default_value = "pipelines.toml"
    )]
    config: PathBuf,

    /// Prometheus metrics listen address. Omit to disable.
    #[arg(long, global = true, env = "DDI_METRICS_ADDR")]
    metrics_addr: Option<String>,

    /// Run only these pipelines, by name. Repeatable. Names match dbt model names when
    /// the config was generated by `ddi dbt convert`.
    #[arg(short = 's', long = "select", global = true, value_name = "NAME")]
    select: Vec<String>,

    /// dbt target to take warehouse credentials from, as `dbt --target` does.
    ///
    /// With this set, table locations are resolved from the catalog rather than guessed
    /// from the manifest, and re-resolved on every poll so a table that moves is followed.
    #[arg(
        short = 't',
        long,
        global = true,
        value_name = "TARGET",
        env = "DDI_TARGET"
    )]
    target: Option<String>,

    /// dbt profile to use. Defaults to the only one in the file.
    #[arg(long, global = true, value_name = "NAME")]
    profile: Option<String>,

    /// Directory holding profiles.yml. Defaults to $DBT_PROFILES_DIR, ./, then ~/.dbt.
    #[arg(long, global = true, value_name = "DIR", env = "DBT_PROFILES_DIR")]
    profiles_dir: Option<PathBuf>,

    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Subcommand)]
enum Command {
    /// Validate the config and exit. Nothing is read or written.
    Validate,
    /// Run every pipeline until each is caught up, then exit.
    Once,
    /// Run continuously (the default).
    Run,
    /// Print each pipeline's resume point and how far behind it is.
    Status,
    /// Work with a dbt project.
    #[command(subcommand)]
    Dbt(DbtCommand),
}

#[derive(Subcommand)]
enum DbtCommand {
    /// Classify every model in a dbt manifest as streamable or not, with reasons.
    Check {
        /// Path to target/manifest.json. Defaults to [dbt].manifest in the config.
        #[arg(long)]
        manifest: Option<PathBuf>,
        /// Show only the models that cannot be streamed.
        #[arg(long)]
        rejected_only: bool,
    },
    /// Emit a pipelines.toml for every streamable model.
    Convert {
        #[arg(long)]
        manifest: Option<PathBuf>,
        /// Write here instead of stdout.
        #[arg(long)]
        out: Option<PathBuf>,
    },
}

/// Default log filter: our own events at info, and the storage stack quiet.
///
/// `buoyant_kernel` is delta-rs's Delta-kernel implementation, and it logs a full snapshot
/// dump per commit at info. Leaving it out of this filter buries every line the daemon
/// actually emits.
const DEFAULT_LOG: &str =
    "info,deltalake=warn,deltalake_core=warn,buoyant_kernel=warn,datafusion=warn";

#[tokio::main]
async fn main() -> std::process::ExitCode {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| DEFAULT_LOG.into()),
        )
        .init();

    let cli = Cli::parse();
    match run(cli).await {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(e) => {
            error!("{e}");
            std::process::ExitCode::FAILURE
        }
    }
}

async fn run(cli: Cli) -> delta_delta_ingest::Result<()> {
    let cfg = Config::from_path(&cli.config)?;

    // The dbt subcommands read a manifest, not the pipeline list, so they must work
    // before any pipelines exist — that is the point at which you are deciding what to
    // put in the config.
    if let Some(Command::Dbt(sub)) = &cli.command {
        return dbt_command(sub, &cfg);
    }

    let all = cfg.resolve()?;
    let pipelines = select(all, &cli.select)?;

    // With a dbt target named, the catalog is the authority on where tables live.
    let locator = Arc::new(build_locator(&cli)?);
    info!(
        config = %cli.config.display(),
        pipelines = pipelines.len(),
        "config valid"
    );

    match cli.command.unwrap_or(Command::Run) {
        Command::Validate => {
            for p in &pipelines {
                // Resolving each backend touches no storage, but it does catch a URI
                // whose scheme was not compiled in and credentials that cannot assemble
                // — both of which would otherwise surface on the first batch.
                p.storage.check(&p.source_uri)?;
                p.storage.check(&p.target_uri)?;
                println!(
                    "{:<24} {} -> {}  (app_id={}, change_policy={:?})",
                    p.name, p.source_uri, p.target_uri, p.app_id, p.change_policy
                );
            }
            println!("\n{} pipeline(s) valid.", pipelines.len());
            Ok(())
        }
        Command::Status => status(pipelines, locator).await,
        Command::Once => run_all(pipelines, locator, cli.metrics_addr, true).await,
        Command::Run => run_all(pipelines, locator, cli.metrics_addr, false).await,
        Command::Dbt(_) => unreachable!("handled above, before the config is resolved"),
    }
}

/// Narrow the pipeline list to `--select`.
///
/// An unknown name is an error rather than an empty run: `ddi -s odrers` should say so,
/// not sit there looking healthy while streaming nothing.
fn select(
    pipelines: Vec<ResolvedPipeline>,
    wanted: &[String],
) -> delta_delta_ingest::Result<Vec<ResolvedPipeline>> {
    if wanted.is_empty() {
        return Ok(pipelines);
    }
    for w in wanted {
        if !pipelines.iter().any(|p| &p.name == w) {
            let mut known: Vec<&str> = pipelines.iter().map(|p| p.name.as_str()).collect();
            known.sort();
            return Err(delta_delta_ingest::Error::Config(format!(
                "--select {w:?} matches no pipeline. Known: [{}]",
                known.join(", ")
            )));
        }
    }
    Ok(pipelines
        .into_iter()
        .filter(|p| wanted.contains(&p.name))
        .collect())
}

fn manifest_path(explicit: &Option<PathBuf>, cfg: &Config) -> delta_delta_ingest::Result<PathBuf> {
    explicit
        .clone()
        .or_else(|| cfg.manifest.as_ref().map(PathBuf::from))
        .ok_or_else(|| {
            delta_delta_ingest::Error::Config(
                "no dbt manifest: pass --manifest, or set `manifest` in the config".into(),
            )
        })
}

fn dbt_command(sub: &DbtCommand, cfg: &Config) -> delta_delta_ingest::Result<()> {
    use delta_delta_ingest::dbt::analyze::{analyze_all, Verdict};
    use delta_delta_ingest::dbt::Manifest;

    match sub {
        DbtCommand::Check {
            manifest,
            rejected_only,
        } => {
            let path = manifest_path(manifest, cfg)?;
            let m = Manifest::from_path(&path)?;
            let verdicts = analyze_all(&m);

            let (mut ok, mut no) = (0, 0);
            for v in &verdicts {
                match v {
                    Verdict::Streamable(s) => {
                        ok += 1;
                        if !rejected_only {
                            println!(
                                "streamable  {:<28} {} -> {}",
                                s.name, s.source_relation, s.target_relation
                            );
                        }
                    }
                    Verdict::Rejected { name, reason } => {
                        no += 1;
                        println!("no          {name:<28} {reason}");
                    }
                }
            }
            println!(
                "\n{ok} streamable, {no} not, of {} model(s).",
                verdicts.len()
            );
            Ok(())
        }
        DbtCommand::Convert { manifest, out } => {
            let path = manifest_path(manifest, cfg)?;
            let m = Manifest::from_path(&path)?;
            let toml = delta_delta_ingest::dbt::convert::to_toml(&m, cfg)?;
            match out {
                Some(p) => {
                    std::fs::write(p, &toml).map_err(delta_delta_ingest::Error::Io)?;
                    println!("wrote {}", p.display());
                }
                None => print!("{toml}"),
            }
            Ok(())
        }
    }
}

/// Build the location resolver from `--target`, if one was named.
fn build_locator(cli: &Cli) -> delta_delta_ingest::Result<Locator> {
    let Some(target) = cli.target.as_deref() else {
        return Ok(Locator::none());
    };
    let path = cli.profiles_dir.as_ref().map(|d| d.join("profiles.yml"));
    let conn = delta_delta_ingest::dbt::profiles::trino_connection(
        path.as_deref(),
        cli.profile.as_deref(),
        Some(target),
    )?;
    info!(target, catalog = %conn.describe(), "resolving table locations from the catalog");
    Ok(Locator::with_client(TrinoClient::new(conn)?))
}

async fn status(
    pipelines: Vec<ResolvedPipeline>,
    locator: Arc<Locator>,
) -> delta_delta_ingest::Result<()> {
    for cfg in pipelines {
        let name = cfg.name.clone();
        let cfg = locator.refresh(&cfg).await;
        match Pipeline::open(cfg).await {
            Ok(p) => println!("{name:<24} resume_from={}", p.cursor()),
            Err(e) => println!("{name:<24} ERROR: {e}"),
        }
    }
    Ok(())
}

async fn run_all(
    pipelines: Vec<ResolvedPipeline>,
    locator: Arc<Locator>,
    metrics_addr: Option<String>,
    once: bool,
) -> delta_delta_ingest::Result<()> {
    let metrics = Metrics::new();
    let token = CancellationToken::new();

    if let Some(addr) = metrics_addr {
        spawn_metrics_server(addr, metrics.clone(), token.clone());
    }

    let mut handles = Vec::new();
    for cfg in pipelines {
        let m = metrics.clone();
        let t = token.clone();
        let l = locator.clone();
        handles.push(tokio::spawn(async move { drive(cfg, l, m, t, once).await }));
    }

    // Graceful shutdown: let the in-flight step finish. A step is atomic, so stopping
    // between steps can never leave a half-applied batch.
    let shutdown = {
        let t = token.clone();
        tokio::spawn(async move {
            let _ = signal::ctrl_c().await;
            warn!("shutdown requested; finishing the current batch then stopping");
            t.cancel();
        })
    };

    let mut failed = false;
    for h in handles {
        match h.await {
            Ok(Ok(())) => {}
            Ok(Err(e)) => {
                error!("pipeline failed: {e}");
                failed = true;
                token.cancel();
            }
            Err(e) => {
                error!("pipeline task panicked: {e}");
                failed = true;
                token.cancel();
            }
        }
    }
    shutdown.abort();

    if failed {
        return Err(delta_delta_ingest::Error::Other(
            "one or more pipelines failed".into(),
        ));
    }
    Ok(())
}

/// One tokio task per pipeline. No coordination between them: masterless, like KDI.
async fn drive(
    cfg: ResolvedPipeline,
    locator: Arc<Locator>,
    metrics: Metrics,
    token: CancellationToken,
    once: bool,
) -> delta_delta_ingest::Result<()> {
    let name = cfg.name.clone();
    let idle = Duration::from_secs(cfg.allowed_latency_secs.max(1));
    let m = metrics.pipeline(&name);

    let mut current = locator.refresh(&cfg).await;
    let mut pipeline = Pipeline::open(current.clone()).await?;

    loop {
        if token.is_cancelled() {
            info!(pipeline = %name, "stopped");
            return Ok(());
        }

        // Ask the catalog where these tables are now. A relocation is invisible in
        // storage — the old table just goes quiet — so the only way to notice is to keep
        // asking. Reopening is safe: a different location is a different table, and the
        // pipeline's own identity check restarts it with the dedup filter suppressing
        // whatever the target already holds.
        let fresh = locator.refresh(&current).await;
        if locate::moved(&current, &fresh) {
            warn!(
                pipeline = %name,
                source = %fresh.source_uri,
                target = %fresh.target_uri,
                "table location changed; reopening"
            );
            current = fresh;
            pipeline = Pipeline::open(current.clone()).await?;
        }

        let outcome = pipeline.step().await;

        // Record head and cursor on every step, including CaughtUp — otherwise the lag
        // gauge freezes at whatever it was when the last batch committed instead of
        // falling to zero once the pipeline has drained the source.
        if let Some(head) = pipeline.source_head_version() {
            m.source_head_version.store(head as i64, Ordering::Relaxed);
        }
        m.cursor_version
            .store(pipeline.cursor().version as i64, Ordering::Relaxed);

        match outcome {
            Ok(StepOutcome::CaughtUp) => {
                if once {
                    info!(pipeline = %name, "caught up");
                    return Ok(());
                }
                tokio::time::sleep(idle).await;
            }
            Ok(StepOutcome::Progressed {
                through_version,
                files,
                rows,
                ..
            }) => {
                m.batches_committed.fetch_add(1, Ordering::Relaxed);
                m.rows_written.fetch_add(rows as u64, Ordering::Relaxed);
                m.files_read.fetch_add(files as u64, Ordering::Relaxed);
                m.last_source_version
                    .store(through_version as i64, Ordering::Relaxed);
            }
            Ok(StepOutcome::Skipped { through_version }) => {
                m.commits_skipped.fetch_add(1, Ordering::Relaxed);
                m.last_source_version
                    .store(through_version as i64, Ordering::Relaxed);
            }
            Err(e) => {
                // A cast failure or a change commit under ChangePolicy::Fail should stop
                // the world, not spin. There is no dead-letter queue by design.
                m.errors.fetch_add(1, Ordering::Relaxed);
                return Err(e);
            }
        }
    }
}

fn spawn_metrics_server(addr: String, metrics: Metrics, token: CancellationToken) {
    tokio::spawn(async move {
        let listener = match tokio::net::TcpListener::bind(&addr).await {
            Ok(l) => l,
            Err(e) => {
                error!("metrics: cannot bind {addr}: {e}");
                return;
            }
        };
        info!(%addr, "metrics listening on /metrics");
        loop {
            if token.is_cancelled() {
                return;
            }
            let Ok((mut sock, _)) = listener.accept().await else {
                continue;
            };
            let body = metrics.render();
            let resp = format!(
                "HTTP/1.1 200 OK\r\nContent-Type: text/plain; version=0.0.4\r\n\
                 Content-Length: {}\r\nConnection: close\r\n\r\n{body}",
                body.len()
            );
            use tokio::io::AsyncWriteExt;
            let _ = sock.write_all(resp.as_bytes()).await;
            let _ = sock.shutdown().await;
        }
    });
}
